name: CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUST_VERSION: 1.93.0
  FORC_VERSION: 0.69.1
  FUEL_CORE_VERSION: 0.48.0

jobs:
  ci:
    runs-on: warp-ubuntu-latest-x64-4x

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY}}
          mode: docker-intercept
          pse_image_tag: "dev-test"
          debug: true
      # ============= InvisiRisk Setup End =============

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy,rustfmt
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-provider: "warpbuild"

      - name: Install forc
        run: |
          curl -sSLf \
            https://github.com/FuelLabs/sway/releases/download/v${{ env.FORC_VERSION }}/forc-binaries-linux_amd64.tar.gz \
            -o forc.tar.gz

          tar -xvf forc.tar.gz

          chmod +x forc-binaries/forc
          chmod +x forc-binaries/forc-fmt

          sudo mv forc-binaries/forc /usr/local/bin/
          sudo mv forc-binaries/forc-fmt /usr/local/bin/

      - name: Install Fuel Core
        run: |
          curl -sSLf \
            https://github.com/FuelLabs/fuel-core/releases/download/v${{ env.FUEL_CORE_VERSION }}/fuel-core-${{ env.FUEL_CORE_VERSION }}-x86_64-unknown-linux-gnu.tar.gz \
            -o fuel-core.tar.gz

          tar -xvf fuel-core.tar.gz

          chmod +x fuel-core-${{ env.FUEL_CORE_VERSION }}-x86_64-unknown-linux-gnu/fuel-core

          sudo mv \
            fuel-core-${{ env.FUEL_CORE_VERSION }}-x86_64-unknown-linux-gnu/fuel-core \
            /usr/local/bin/fuel-core

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --all-features --verbose

      - name: Test
        run: cargo test --all-features --workspace --verbose

      - name: Check Sway formatting
        run: forc fmt --check --path e2e

      - name: Build Sway projects
        run: forc build --release --terse --error-on-warnings --path e2e

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
